name: Pura CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: 'latest'
          stack-version: 'latest'

      - name: Cache stack dependencies
        uses: actions/cache@v4
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Install dependencies
        run: stack build --dependencies-only


      - name: Build project
        run: stack build

      - name: Run tests
        run: stack test
